# _config.yml
title: Aaron Zhou — Firmware, Systems & Applied AI
description: Notes from building reliable firmware, test rigs, and practical ML at the edge.
theme: minima
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

permalink: /posts/:slug/
